on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan mainline branches and report all findings: 
  push:
    branches: ["master", "main"]
  # Schedule the CI job (this method uses cron syntax):
  
  schedule:
    - cron:  '0 1 * * 6'
  
name: Semgrep SAST Scan
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep
    steps:
    - name: Checkout rules
      uses: actions/checkout@v3
      with:
        repository: wintermute404/semgrep-rules
        path: ./rules
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: wintermute404/DVWA
        path: ./code
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run all the rules 
      id: run_rules_nonpr
      run: |
        semgrep scan --sarif --metrics=off --config=./rules/ ./code > nonpr.sarif;
